const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const today = new Date();
const pad = n => String(n).padStart(2, '0');
const iso = d => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
const dateFrom = s => { const [y, m, d] = s.split('-').map(Number); return new Date(y, m - 1, d); };
const start = d => new Date(d.getFullYear(), d.getMonth(), d.getDate());
const sameDay = (a, b) => start(a).getTime() === start(b).getTime();
const daysBetween = (a, b) => Math.round((start(b) - start(a)) / 86400000);
const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const lunarDayNames = ['','初一','初二','初三','初四','初五','初六','初七','初八','初九','初十','十一','十二','十三','十四','十五','十六','十七','十八','十九','二十','廿一','廿二','廿三','廿四','廿五','廿六','廿七','廿八','廿九','三十'];
const standardLunarMonth = month => ({'冬月':'十一月','腊月':'十二月'})[month] || month;
const lunarCache = new Map();
const lunarParts = d => { const key=iso(d); if(lunarCache.has(key))return lunarCache.get(key); try { const parts=new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{year:'numeric',month:'long',day:'numeric'}).formatToParts(d), value=t=>parts.find(p=>p.type===t)?.value||''; const rawDay=parseInt(value('day'),10),result={month:standardLunarMonth(value('month')),day:lunarDayNames[rawDay]||value('day'),dayNumber:rawDay,yearName:value('yearName'),relatedYear:parseInt(value('relatedYear'),10)||d.getFullYear()}; lunarCache.set(key,result); return result; } catch { return {month:'',day:'农历',dayNumber:0,yearName:'',relatedYear:d.getFullYear()}; } };
const lunar = d => { const p=lunarParts(d); return `${p.month}${p.day}`; };
const lunarShort = d => { const p=lunarParts(d); return p.dayNumber===1?p.month:p.day; };
const lunarYear = d => { const p=lunarParts(d), zodiac=['猴','鸡','狗','猪','鼠','牛','虎','兔','龙','蛇','马','羊'][((p.relatedYear%12)+12)%12]; return p.yearName?`${p.yearName}年 · ${zodiac}年`:`${p.relatedYear}年`; };
const solarHoliday = {'01-01':'元旦','01-10':'中国人民警察节','02-14':'情人节','03-05':'学雷锋纪念日','03-08':'妇女节','03-12':'植树节','03-15':'消费者权益日','04-01':'愚人节','04-22':'世界地球日','05-01':'劳动节','05-04':'青年节','05-12':'护士节','06-01':'儿童节','07-01':'建党节','08-01':'建军节','09-03':'抗战胜利纪念日','09-10':'教师节','09-18':'九一八纪念日','10-01':'国庆节','11-11':'双十一','12-13':'南京大屠杀死难者国家公祭日','12-25':'圣诞节'};
const lunarHoliday = {'正月初一':'春节','正月十五':'元宵节','二月初二':'龙抬头','三月初三':'上巳节','五月初五':'端午节','七月初七':'七夕','七月十五':'中元节','八月十五':'中秋节','九月初九':'重阳节','十月初一':'寒衣节','十月十五':'下元节','腊月初八':'腊八节','腊月廿三':'北方小年','腊月廿四':'南方小年','十二月初八':'腊八节','十二月廿三':'北方小年','十二月廿四':'南方小年'};
const official2026 = {};
const markOfficial = (status, label, dates) => dates.forEach(s => { official2026[`2026-${s}`] = { status, label }; });
markOfficial('rest','元旦',['01-01','01-02','01-03']); markOfficial('work','调休上班',['01-04']);
markOfficial('rest','春节',['02-15','02-16','02-17','02-18','02-19','02-20','02-21','02-22','02-23']); markOfficial('work','调休上班',['02-14','02-28']);
markOfficial('rest','清明节',['04-04','04-05','04-06']); markOfficial('rest','劳动节',['05-01','05-02','05-03','05-04','05-05']); markOfficial('work','调休上班',['05-09']);
markOfficial('rest','端午节',['06-19','06-20','06-21']); markOfficial('rest','中秋节',['09-25','09-26','09-27']);
markOfficial('rest','国庆节',['10-01','10-02','10-03','10-04','10-05','10-06','10-07']); markOfficial('work','调休上班',['09-20','10-10']);
const terms = [['小寒',1,5],['大寒',1,20],['立春',2,4],['雨水',2,19],['惊蛰',3,5],['春分',3,20],['清明',4,5],['谷雨',4,20],['立夏',5,5],['小满',5,21],['芒种',6,6],['夏至',6,21],['小暑',7,7],['大暑',7,23],['立秋',8,7],['处暑',8,23],['白露',9,7],['秋分',9,23],['寒露',10,8],['霜降',10,23],['立冬',11,7],['小雪',11,22],['大雪',12,7],['冬至',12,22]];
const terms2026 = {'2026-01-05':'小寒','2026-01-20':'大寒','2026-02-04':'立春','2026-02-18':'雨水','2026-03-05':'惊蛰','2026-03-20':'春分','2026-04-05':'清明','2026-04-20':'谷雨','2026-05-05':'立夏','2026-05-21':'小满','2026-06-05':'芒种','2026-06-21':'夏至','2026-07-07':'小暑','2026-07-23':'大暑','2026-08-07':'立秋','2026-08-23':'处暑','2026-09-07':'白露','2026-09-23':'秋分','2026-10-08':'寒露','2026-10-23':'霜降','2026-11-07':'立冬','2026-11-22':'小雪','2026-12-07':'大雪','2026-12-22':'冬至'};
const termNotes = {'立春':'春季开始，万物复苏。','雨水':'气温回升，降水渐增。','惊蛰':'春雷始鸣，蛰虫萌动。','春分':'昼夜近乎等长。','清明':'气清景明，适宜踏青。','谷雨':'春雨增多，利于谷物生长。','立夏':'夏季开始，万物繁茂。','小满':'麦类等夏熟作物渐饱满。','芒种':'有芒作物成熟，进入忙种时节。','夏至':'北半球白昼接近全年最长。','小暑':'天气开始炎热。','大暑':'一年中炎热集中的时节。','立秋':'秋季开始，暑热未尽。','处暑':'暑气渐退。','白露':'昼夜温差增大，露水渐显。','秋分':'昼夜近乎等长。','寒露':'露气寒冷，将凝结为霜。','霜降':'秋季最后一个节气。','立冬':'冬季开始，万物收藏。','小雪':'气温下降，开始出现降雪。','大雪':'气温继续降低，降雪可能增多。','冬至':'北半球白昼接近全年最短。','小寒':'进入一年中寒冷时段。','大寒':'二十四节气的最后一个节气。'};
const festivalNotes = {'春节':'农历新年，辞旧迎新、阖家团圆。','元宵节':'农历正月十五，赏灯、吃元宵。','清明节':'祭扫追思、踏青亲近自然。','端午节':'纪念传统文化，常见习俗有赛龙舟、食粽。','七夕':'源于牛郎织女传说的传统节日。','中秋节':'赏月、团圆、食月饼。','重阳节':'登高敬老，农历九月初九。','除夕':'农历年的最后一天，阖家守岁。','国庆节':'中华人民共和国成立纪念日。','劳动节':'向劳动者致敬的节日。','母亲节':'表达对母亲感谢的纪念日。','父亲节':'表达对父亲感谢的纪念日。'};
const solarTerm = d => terms2026[iso(d)] || terms.find(x => x[1]===d.getMonth()+1 && x[2]===d.getDate())?.[0] || '';
const weekdayFestival = d => { const m=d.getMonth()+1,n=d.getDate(),w=d.getDay(),order=Math.ceil(n/7); if(m===5&&w===0&&order===2)return'母亲节'; if(m===6&&w===0&&order===3)return'父亲节'; if(m===11&&w===4&&order===4)return'感恩节'; return ''; };
const festivalName = d => { const key=`${pad(d.getMonth()+1)}-${pad(d.getDate())}`, fixed=solarHoliday[key]||lunarHoliday[lunar(d)]||weekdayFestival(d); if(fixed)return fixed; if(solarTerm(d)==='清明')return'清明节'; const next=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1); return lunar(next)==='正月初一'?'除夕':''; };
const dateMeta = d => { const official=official2026[iso(d)], festival=festivalName(d); if(official)return {...official,festival}; return festival?{status:'festival',label:festival,festival}:{}; };
const holiday = d => dateMeta(d).festival || dateMeta(d).label || '';
const constellation = d => { const m=d.getMonth()+1,n=d.getDate(); if((m===3&&n>=21)||(m===4&&n<=19))return'白羊座';if((m===4&&n>=20)||(m===5&&n<=20))return'金牛座';if((m===5&&n>=21)||(m===6&&n<=21))return'双子座';if((m===6&&n>=22)||(m===7&&n<=22))return'巨蟹座';if((m===7&&n>=23)||(m===8&&n<=22))return'狮子座';if((m===8&&n>=23)||(m===9&&n<=22))return'处女座';if((m===9&&n>=23)||(m===10&&n<=23))return'天秤座';if((m===10&&n>=24)||(m===11&&n<=22))return'天蝎座';if((m===11&&n>=23)||(m===12&&n<=21))return'射手座';if((m===12&&n>=22)||(m===1&&n<=19))return'摩羯座';if((m===1&&n>=20)||(m===2&&n<=18))return'水瓶座';return'双鱼座'; };
const dayOfYear = d => Math.floor((start(d)-new Date(d.getFullYear(),0,1))/86400000)+1;
const daysInYear = y => new Date(y,1,29).getMonth()===1?366:365;
const weekNumber = d => { const first=new Date(d.getFullYear(),0,1),offset=(first.getDay()+6)%7; return Math.ceil((dayOfYear(d)+offset)/7); };
const kindIcon = k => ({countdown:'⌛',anniversary:'♥',birthday:'🎂',general:'□'})[k] || '○';
const kindName = k => ({countdown:'倒数日',anniversary:'纪念日',birthday:'生日',general:'事项'})[k] || '事项';
const loadEvents = () => { try { const data=JSON.parse(localStorage.getItem('suishi-events')||'[]'); return Array.isArray(data)?data:[]; } catch { return []; } };
let events = loadEvents();
let cursor = new Date(today.getFullYear(), today.getMonth(), 1), selected = new Date(today);
const save = () => localStorage.setItem('suishi-events', JSON.stringify(events));
const nextDate = e => { if (!e.repeat) return dateFrom(e.date); const original=dateFrom(e.date), y=today.getFullYear(); const current=new Date(y,original.getMonth(),original.getDate()); return start(current)<start(today)?new Date(y+1,original.getMonth(),original.getDate()):current; };
const delta = e => daysBetween(today, nextDate(e));
const deltaText = n => n===0?'今天':n>0?`还有 ${n} 天`:`已过去 ${-n} 天`;
const eventOn = d => events.filter(e => sameDay(nextDate(e), d) || (e.repeat && dateFrom(e.date).getMonth()===d.getMonth() && dateFrom(e.date).getDate()===d.getDate()));
const upcomingTerm = from => { for(let i=0;i<370;i++){const d=new Date(from.getFullYear(),from.getMonth(),from.getDate()+i);const name=solarTerm(d);if(name)return {date:d,name};} return null; };
const upcomingHoliday = from => { for(let i=0;i<370;i++){const d=new Date(from.getFullYear(),from.getMonth(),from.getDate()+i),meta=dateMeta(d);if(meta.status==='rest'&&start(d)>=start(from))return {date:d,name:meta.label};} return null; };
const officialPeriodLabel = d => { const meta=official2026[iso(d)]; if(!meta||meta.status!=='rest')return''; const prev=new Date(d.getFullYear(),d.getMonth(),d.getDate()-1),previous=official2026[iso(prev)]; return !previous||previous.status!==meta.status||previous.label!==meta.label?`${meta.label}假期`:''; };

function renderToday() {
  const h=holiday(today), term=solarTerm(today), sorted=[...events].sort((a,b)=>nextDate(a)-nextDate(b)), next=sorted.find(e=>nextDate(e)>=start(today)) || sorted[0], upcoming=upcomingTerm(new Date(today.getFullYear(),today.getMonth(),today.getDate()+1)), nextHoliday=upcomingHoliday(new Date(today.getFullYear(),today.getMonth(),today.getDate()+1));
  const info=[['农历',lunar(today)],['干支生肖',lunarYear(today)],['星座',constellation(today)],['时间位置',`第 ${weekNumber(today)} 周 · ${dayOfYear(today)} 天`]];
  const agenda=[...Array(7)].map((_,i)=>new Date(today.getFullYear(),today.getMonth(),today.getDate()+i)).map(d=>({date:d,items:eventOn(d)})).filter(x=>x.items.length);
  const progress=Math.round(dayOfYear(today)/daysInYear(today.getFullYear())*100); $('#todayContent').innerHTML=`<div class="hero"><div class="date">${today.toLocaleDateString('zh-CN',{year:'numeric',month:'long'})} · ${today.toLocaleDateString('zh-CN',{weekday:'long'})}</div><div class="hero-line"><div class="hero-day">${today.getDate()}</div><div class="hero-week">${today.toLocaleDateString('zh-CN',{weekday:'long'})}</div></div><div class="lunar">农历 ${lunar(today)} · ${lunarYear(today)}</div>${h?`<div class="holiday">✦ ${h}</div>`:''}${term?`<div class="term-badge">☼ 今日节气 · ${term}</div>`:''}</div>${next?`<div class="next-card"><div><div class="next-label">最近的日子 · ${kindName(next.kind)}</div><h3>${esc(next.name)}</h3><time>${nextDate(next).toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'})}</time></div><div class="next-number"><strong>${Math.abs(delta(next))}</strong><span>${delta(next)===0?'就是今天':delta(next)>0?'天后':'天前'}</span></div></div>`:''}<div class="info-grid">${info.map(x=>`<div class="info-item"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><div class="card almanac"><div class="card-heading"><h3>今日生活提示</h3><span>非传统黄历</span></div><div class="yi-ji"><div><b>适合</b><p>阅读 · 整理 · 出行 · 记录</p></div><div><b>提醒</b><p>少熬夜 · 少拖延 · 记住重要的人</p></div></div></div><div class="card rhythm"><div class="card-heading"><h3>时间提示</h3><span>${upcoming?`下个节气 · ${upcoming.name}`:'二十四节气'}</span></div><div class="rhythm-row"><span>今日是一年中的第 ${dayOfYear(today)} 天</span><strong>${progress}%</strong></div><div class="progress"><i style="width:${progress}%"></i></div>${upcoming?`<small>${upcoming.date.toLocaleDateString('zh-CN',{month:'long',day:'numeric'})} · ${termNotes[upcoming.name]||''}</small>`:''}${nextHoliday?`<div class="next-holiday"><span>下个法定假期</span><strong>${nextHoliday.name}</strong><time>${nextHoliday.date.toLocaleDateString('zh-CN',{month:'long',day:'numeric'})} · 还有 ${daysBetween(today,nextHoliday.date)} 天</time></div>`:''}</div>${agenda.length?`<div class="card agenda"><div class="card-heading"><h3>未来 7 天</h3><button class="text-btn" onclick="switchPage('eventsPage')">查看全部</button></div>${agenda.map(x=>`<div class="agenda-row"><time>${x.date.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric',weekday:'short'})}</time><div>${x.items.map(e=>`<span>${kindIcon(e.kind)} ${esc(e.name)}</span>`).join('')}</div></div>`).join('')}</div>`:''}<div class="mini-grid">${sorted.slice(0,4).map(e=>`<div class="mini"><div class="symbol">${kindIcon(e.kind)}</div><b>${esc(e.name)}</b><small>${deltaText(delta(e))}</small></div>`).join('')||'<div class="card empty" style="grid-column:1/-1">还没有日子，去“我的日子”添加一个吧</div>'}</div>`;
}

function renderCalendar() {
  const y=cursor.getFullYear(),m=cursor.getMonth(); $('#monthLabel').textContent=`${y}年${m+1}月`; $('#monthPicker').value=`${y}-${pad(m+1)}`; const first=new Date(y,m,1),offset=first.getDay(),days=new Date(y,m+1,0).getDate(); let html='';
  for(let i=0;i<42;i++){const n=i-offset+1,d=new Date(y,m,n),inMonth=n>0&&n<=days,sel=sameDay(d,selected),items=eventOn(d),meta=dateMeta(d),term=solarTerm(d),mark=festivalName(d)||term||officialPeriodLabel(d);html+=`<button class="day ${inMonth?'':'muted'} ${sameDay(d,today)?'today':''} ${sel?'selected':''} ${meta.status||''}" data-date="${iso(d)}"><span class="day-num">${d.getDate()}</span><span class="day-lunar">${lunarShort(d)}</span>${mark?`<span class="day-mark ${term&&!festivalName(d)?'term-mark':''}">${mark}</span>`:''}${meta.status==='rest'||meta.status==='work'?`<i class="status-badge">${meta.status==='rest'?'休':'班'}</i>`:''}${items.length?`<i class="event-dot">${items.length}</i>`:''}</button>`}
  $('#calendarGrid').innerHTML=html; $$('.day').forEach(b=>b.onclick=()=>{selected=dateFrom(b.dataset.date);if(selected.getFullYear()!==y||selected.getMonth()!==m)cursor=new Date(selected.getFullYear(),selected.getMonth(),1);renderCalendar()}); renderMonthSummary(y,m,days); renderSelectedInfo();
}
function renderMonthSummary(y,m,days){const list=[...Array(days)].map((_,i)=>new Date(y,m,i+1)),rest=list.filter(d=>dateMeta(d).status==='rest').length,work=list.filter(d=>dateMeta(d).status==='work').length,festivalList=list.map(d=>({date:d,name:festivalName(d)})).filter(x=>x.name),termList=list.map(d=>({date:d,name:solarTerm(d)})).filter(x=>x.name),sourceNote=y===2026?'2026 休班与节气已核对':'节气按常见日期参考';$('#monthSummary').innerHTML=`<div class="summary-title"><strong>${y}年${m+1}月概览</strong><span>${sourceNote}</span></div><div class="summary-stats"><span><b>${rest}</b> 天休息</span><span><b>${work}</b> 天调休上班</span><span><b>${festivalList.length}</b> 个节日</span><span><b>${termList.length}</b> 个节气</span></div>${festivalList.length?`<div class="summary-list"><b>本月节日</b>${festivalList.map(x=>`<span>${x.date.getDate()}日 ${x.name}</span>`).join('')}</div>`:''}${termList.length?`<div class="summary-list"><b>本月节气</b>${termList.map(x=>`<span>${x.date.getDate()}日 ${x.name}</span>`).join('')}</div>`:''}`;}
function renderSelectedInfo(){const meta=dateMeta(selected),h=festivalName(selected)||officialPeriodLabel(selected),t=solarTerm(selected),items=eventOn(selected),status=meta.status==='rest'?'法定休息日':meta.status==='work'?'调休上班日':'',p=lunarParts(selected),cultureNote=festivalNotes[h]||termNotes[t]||'';$('#selectedInfo').innerHTML=`<div class="selected-date-head"><div><span>${selected.toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span><strong>农历${p.month}${p.day}</strong></div><button class="add-selected" onclick="openEditorForSelected()">＋ 添加事项</button></div><div class="selected-chips"><span>${lunarYear(selected)}</span><span>${constellation(selected)}</span><span>第 ${weekNumber(selected)} 周</span><span>年第 ${dayOfYear(selected)} 天</span>${status?`<em class="status-${meta.status}">${status}</em>`:''}${h?`<em>节 · ${h}</em>`:''}${t?`<em class="term-inline">气 · ${t}</em>`:''}</div>${cultureNote?`<div class="culture-note"><b>${h||t}</b><span>${cultureNote}</span></div>`:''}<div class="selected-events"><div class="selected-events-title"><b>当天事项</b><span>${items.length} 项</span></div>${items.length?items.map(e=>`<div>${kindIcon(e.kind)} ${esc(e.name)} <small>${deltaText(delta(e))}</small></div>`).join(''):'<p class="muted">暂无事项，可以为这一天添加纪念、生日或提醒。</p>'}</div>`;}
function renderEvents(){if(!events.length){$('#eventList').innerHTML='<div class="empty">还没有记录<br><button class="primary small" style="margin:18px auto;width:auto" onclick="openEditor()">＋ 新建第一个日子</button></div>';return}const groups={countdown:'倒数日',anniversary:'纪念日',birthday:'生日',general:'事项'};let html='';Object.entries(groups).forEach(([k,v])=>{const list=events.filter(e=>e.kind===k).sort((a,b)=>nextDate(a)-nextDate(b));if(!list.length)return;html+=`<div class="event-group"><h3>${v} · ${list.length}</h3>${list.map(e=>`<div class="event-card" data-id="${e.id}"><div class="event-icon">${kindIcon(e.kind)}</div><div class="event-body"><b>${esc(e.name)}</b><small>${nextDate(e).toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'})}${e.repeat?' · 每年':''}${e.note?` · ${esc(e.note)}`:''}</small></div><div class="event-delta">${deltaText(delta(e))}</div><button class="icon-btn delete" aria-label="删除">×</button></div>`).join('')}</div>`});$('#eventList').innerHTML=html;$$('.event-card').forEach(c=>{c.onclick=e=>{if(!e.target.classList.contains('delete'))openEditor(events.find(x=>x.id===c.dataset.id))};c.querySelector('.delete').onclick=()=>{events=events.filter(x=>x.id!==c.dataset.id);save();renderEvents();renderToday()}})}
function openEditor(e,presetDate){$('#eventId').value=e?.id||'';$('#eventName').value=e?.name||'';$('#eventKind').value=e?.kind||'countdown';$('#eventDate').value=e?.date||presetDate||iso(today);$('#eventRepeat').checked=!!e?.repeat;$('#eventNote').value=e?.note||'';$('#eventReminder').value=e?.reminder??'';$('#dialogTitle').textContent=e?'编辑日子':'新建日子';$('#eventDialog').showModal()}
$('#eventForm').onsubmit=ev=>{ev.preventDefault();const id=$('#eventId').value||crypto.randomUUID();events=events.filter(e=>e.id!==id);events.push({id,name:$('#eventName').value.trim(),kind:$('#eventKind').value,date:$('#eventDate').value,repeat:$('#eventRepeat').checked,note:$('#eventNote').value,reminder:$('#eventReminder').value});save();$('#eventDialog').close();renderEvents();renderToday()};
function switchPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.page===id));document.body.classList.toggle('calendar-open',id==='calendarPage');if(id==='calendarPage')renderCalendar();if(id==='eventsPage')renderEvents();if(id==='todayPage')renderToday()}
const moveMonth = step => { const next=new Date(cursor.getFullYear(),cursor.getMonth()+step,1),lastDay=new Date(next.getFullYear(),next.getMonth()+1,0).getDate(); cursor=next; selected=new Date(next.getFullYear(),next.getMonth(),Math.min(selected.getDate(),lastDay)); renderCalendar(); };
$$('.tab').forEach(t=>t.onclick=()=>switchPage(t.dataset.page)); $('#addBtn').onclick=()=>openEditor(); window.openEditor=openEditor; window.openEditorForSelected=()=>openEditor(undefined,iso(selected)); window.switchPage=switchPage; $('#prevMonth').onclick=()=>moveMonth(-1); $('#nextMonth').onclick=()=>moveMonth(1); $('#monthPicker').onchange=e=>{const [y,m]=e.target.value.split('-').map(Number);if(y&&m){cursor=new Date(y,m-1,1);selected=new Date(y,m-1,1);renderCalendar()}}; $('#calendarToday').onclick=()=>{cursor=new Date(today.getFullYear(),today.getMonth(),1);selected=new Date(today);renderCalendar()}; $('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('suishi-dark',document.body.classList.contains('dark'))}; if(localStorage.getItem('suishi-dark')==='true')document.body.classList.add('dark'); $('#notifyBtn').onclick=async()=>{if(!('Notification'in window)){$('#notifyStatus').textContent='当前浏览器不支持通知';return}const p=await Notification.requestPermission();$('#notifyStatus').textContent=p==='granted'?'通知已开启':'未获得通知权限'};
if($('#quitBtn'))$('#quitBtn').onclick=()=>{if(window.webkit?.messageHandlers?.quitApp)window.webkit.messageHandlers.quitApp.postMessage('quit');else alert('请关闭当前页面以退出');}; if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{}); renderToday();
